Iter9
igortoigildin/go-metrics-altering pull request #21
Opened 2024-07-02 11:39 UTC by igortoigildin

2024-07-03 10:38 UTC, tmvrus requested changes
Есть вопросы

2024-07-03 10:38 UTC, tmvrus commented on internal/config/server_config/config_server.go
в пути тра раза встречается слово config и 2 раза слово server, возможно стоит попробовать избавиться от дублирования server\config или config\server будет меньше "шума"

2024-07-03 10:38 UTC, tmvrus commented on internal/server/handlers.go
> +		logger.Log.Info("error parcing bool flag", zap.Error(err))
тут видимо опечатка в слове parcing

2024-07-03 10:38 UTC, tmvrus commented on internal/server/storage.go
> +        logger.Log.Debug("cannot decode time interval", zap.Error(err))
код продолжит работать, даже если нет интервала, не думаю что это правильно
хорошим тоном считается передавать уже готовые данные для работы, которые не нужно парсить, тогда ошибку обрабатывать не придется

2024-07-03 10:38 UTC, tmvrus commented on internal/server/storage.go
> +        Save(cfg.FlagStorePath, metricSlice)
ошибка никак не обрабатывается, это затруднит отладку и сопровождение системы

2024-07-03 10:38 UTC, tmvrus commented on templates/fs.go
>  //go:embed *
все же стоит указать конкретный файл с которым идет работа

2024-07-03 10:38 UTC, tmvrus commented on internal/server/handlers.go
> +        m.Load(cfg.FlagStorePath)
ошибка никак не обрабатывается

2024-07-03 10:38 UTC, tmvrus commented on internal/server/handlers.go
> +        w.WriteHeader(http.StatusInternalServerError)
если пользователь прислал невалидный JSON хорошо бы ему ответить BadRequest что бы он знал что сам виноват, в данном случае он будет думать что у сервера что-то не так

2024-07-03 10:38 UTC, tmvrus commented on internal/server/handlers.go
> +        }
тут что-то с форматированием, попробуй прогнать gofmt

2024-07-03 10:38 UTC, tmvrus commented on internal/server/handlers.go
> +    fmt.Println("finish")
не стоит использовать fmt для логирования, раз уж есть логер

2024-07-03 10:38 UTC, tmvrus commented on internal/server/handlers.go
> +        if err != nil {
ошибку стоит хотя бы залогировать, что бы знать что конкретно не понравилось парсеру

2024-07-03 10:38 UTC, tmvrus commented on internal/server/handlers.go
> +            rw.WriteHeader(http.StatusBadRequest)
тоже самое

2024-07-03 10:38 UTC, tmvrus commented on internal/server/handlers.go
> +        rw.Write([]byte(strconv.FormatFloat(m.GetGaugeMetricFromMemory(metricName),'f', -1, 64)))
ошибка не обрабатывается

2024-07-03 10:38 UTC, tmvrus commented on internal/server/handlers.go
> +        rw.Write([]byte(strconv.FormatInt(m.GetCountMetricFromMemory(metricName), 10)))
и тут

2024-07-03 10:38 UTC, tmvrus commented on internal/server/handlers.go
> +        log.Printf("Failed to execute template: %v", err)
почему тут не logger.Log ?

2024-07-03 10:38 UTC, tmvrus commented on internal/server/storage.go
> +    var model models.Metrics
можно было заранее выделить нужное количество элементов слайса, используя make, поскольку это количество известно

2024-07-03 10:38 UTC, tmvrus commented on internal/server/storage.go
> +        model.MType = "counter"
для этих строковых значений уже есть константы в проекте, почему бы их не использовать?

2024-07-03 10:38 UTC, tmvrus commented on internal/server/server.go
> +    c := make(map[string]interface{})
размер результата известен, значит можно заранее выделить

2024-07-07 11:35 UTC, igortoigildin commented on internal/config/server_config/config_server.go
вынес директорию конфиг в корневую дерикторию и изменил названия соответственно

2024-07-07 11:36 UTC, igortoigildin commented on internal/server/handlers.go
> +		logger.Log.Info("error parcing bool flag", zap.Error(err))
исправил

2024-07-07 11:36 UTC, igortoigildin commented on internal/server/storage.go
> +        logger.Log.Debug("cannot decode time interval", zap.Error(err))
Перенес парсинг в LoadConfig, добавил проверки на пустые значения параметров Config

2024-07-07 11:37 UTC, igortoigildin commented on internal/server/storage.go
> +        Save(cfg.FlagStorePath, metricSlice)
добавил обработку ошибки

2024-07-07 11:37 UTC, igortoigildin commented on templates/fs.go
>  //go:embed *
Добавил

2024-07-07 11:37 UTC, igortoigildin commented on internal/server/handlers.go
> +        m.Load(cfg.FlagStorePath)
добавил обработку ошибки

2024-07-07 11:37 UTC, igortoigildin commented on internal/server/handlers.go
> +        w.WriteHeader(http.StatusInternalServerError)
Исправил

2024-07-07 11:37 UTC, igortoigildin commented on internal/server/handlers.go
> +        }
прогнал gofmt

2024-07-07 11:37 UTC, igortoigildin commented on internal/server/handlers.go
> +    fmt.Println("finish")
исправил

2024-07-07 11:38 UTC, igortoigildin commented on internal/server/handlers.go
> +        if err != nil {
Добавил логирование

2024-07-07 11:38 UTC, igortoigildin commented on internal/server/handlers.go
> +            rw.WriteHeader(http.StatusBadRequest)
Добавил логирование

2024-07-07 11:38 UTC, igortoigildin commented on internal/server/handlers.go
> +        rw.Write([]byte(strconv.FormatFloat(m.GetGaugeMetricFromMemory(metricName),'f', -1, 64)))
Добавил обработку ошибки

2024-07-07 11:38 UTC, igortoigildin commented on internal/server/handlers.go
> +        rw.Write([]byte(strconv.FormatInt(m.GetCountMetricFromMemory(metricName), 10)))
Добавил обработку ошибки

2024-07-07 11:38 UTC, igortoigildin commented on internal/server/handlers.go
> +        log.Printf("Failed to execute template: %v", err)
исправил

2024-07-07 11:39 UTC, igortoigildin commented on internal/server/storage.go
> +    var model models.Metrics
Добавил длину в make

2024-07-07 11:39 UTC, igortoigildin commented on internal/server/storage.go
> +        model.MType = "counter"
Добавил

2024-07-07 11:39 UTC, igortoigildin commented on internal/server/server.go
> +    c := make(map[string]interface{})
Добавил длину

2024-07-08 06:27 UTC, tmvrus approved these changes

2024-07-09 17:54 UTC, merged