Iter13
igortoigildin/go-metrics-altering pull request #30
Opened 2024-07-16 20:55 UTC by igortoigildin

2024-07-17 10:01 UTC, tmvrus requested changes
- Exist все еще выглядит лишним
- использовать log.Fatal на уровне хранения недопустимо, это угрожает всему приложению
- если нужно выполнить 1 запрос, то оборачивать его в транзакцию нет никакого смысла

2024-07-17 10:01 UTC, tmvrus commented on config/agent/config.go
> +	FlagLogLevel		string
тут видимо поехало форматирование

2024-07-17 10:01 UTC, tmvrus commented on internal/agent/agent.go
> +        logger.Log.Debug("unexpected sending metric error:", zap.Error(err))
не думаю что нужно продолжать работу если случилась ошибка, ее нужно хотя бы залогировать
либо, что лучше, изменить сигнатуру ф-и таким образом что бы она могла вернуть ошибку

2024-07-17 10:01 UTC, tmvrus commented on internal/agent/agent.go
> +            }
не выглядит этот цикл как хорошо читаемый код: несколько счетчиков, разные способы их увеличения, 
суть ведь в том, что бы сделать несколько запросов до победного, но с разной задержкой, вполне можно обойтись вот таким циклом
```go
for _, delay := range []time.Duration{time.Second, 2*time.Second, 3*time.Second} {
		time.Sleep(delay)
		// выполнить работу
	}
```
или чем-то похожим, главное что кода меньше и сложность ниже

2024-07-17 10:01 UTC, tmvrus commented on internal/agent/agent.go
> +        metrics = metrics[:0]
вот этот загадочный ход выглядит лишним, как собственно и переменная

2024-07-17 10:01 UTC, tmvrus commented on internal/agent/agent.go
> +func PrepareMetricBodyNew(cfg *config.ConfigAgent, metricName string) models.Metrics {
название на мой взгляд можно упростить sendJSONMetic будет понятно что делает ф-я
текущее название содержит New неясно зачем
и не отражает фактического содержания ф-и

2024-07-17 10:01 UTC, tmvrus commented on internal/server/app.go
> +            if app.storage.Exist(ctx, metric.MType, metric.ID) {
о сомнительной ценности этой ф-и мы говорили на 1-1
postgresql поддерживает INSERT ON CONFLITC и дополнительный поход в базу не нужен.

2024-07-17 10:01 UTC, tmvrus commented on internal/storage/repository.go
> +	}
тут нет никакого смысла в тразнакции, ведь выполнить нужно только один запрос, база сама обернет его.

2024-07-17 10:01 UTC, tmvrus commented on internal/storage/repository.go
> +		case err == sql.ErrNoRows:
такой способ сравнения ошибок ненадежен, так как не гарантирует обратной совместимости
рекомендую тут и далее использовать errors.Is

2024-07-17 10:01 UTC, tmvrus commented on internal/storage/repository.go
> +			return metric, err
log.Fatal моментально завершит работу приложения, до следующей строки управление даже не дойдет
использовать такой уровень логирования когда приложение уже запущено и работает - довольно странный выбор, ведь любая минимальная ошибка(даже сетевая) может привести к краху всего приложения

2024-07-17 10:01 UTC, tmvrus commented on internal/storage/repository.go
> +	rep.conn.Close()
не до конца ясно зачем закрывать конект после пинга

2024-07-17 10:01 UTC, tmvrus commented on internal/storage/repository.go
> +	}
дизайн довольно странный, с одной стороны работа идет у уровне репозитория, с другой, используются типы из пакета http
это выглядит как классическая "протекающая" абстракция, когда один слой отвечает за несколько задачь
этого следует избегать, это нарушение принципа единой ответственности

2024-07-20 12:26 UTC, igortoigildin commented on config/agent/config.go
> +	FlagLogLevel		string
прогнал go fmt

2024-07-20 12:26 UTC, igortoigildin commented on internal/agent/agent.go
> +        logger.Log.Debug("unexpected sending metric error:", zap.Error(err))
добавил логирование и возврат ошибки

2024-07-20 12:27 UTC, igortoigildin commented on internal/agent/agent.go
> +            }
обновил

2024-07-20 12:27 UTC, igortoigildin commented on internal/agent/agent.go
> +        metrics = metrics[:0]
убрал

2024-07-20 12:27 UTC, igortoigildin commented on internal/agent/agent.go
> +func PrepareMetricBodyNew(cfg *config.ConfigAgent, metricName string) models.Metrics {
обноавил названия, сделал полный рефакторинг кода агента

2024-07-20 12:28 UTC, igortoigildin commented on internal/server/app.go
> +            if app.storage.Exist(ctx, metric.MType, metric.ID) {
убрал exists, добавил INSERT ON CONFLITC

2024-07-20 12:28 UTC, igortoigildin commented on internal/storage/repository.go
> +	}
Убрал транзакции

2024-07-20 12:29 UTC, igortoigildin commented on internal/storage/repository.go
> +		case err == sql.ErrNoRows:
Обновил

2024-07-20 12:30 UTC, igortoigildin commented on internal/storage/repository.go
> +			return metric, err
убрал fatal из всего слоя

2024-07-20 12:30 UTC, igortoigildin commented on internal/storage/repository.go
> +	rep.conn.Close()
убрал

2024-07-20 12:32 UTC, igortoigildin commented on internal/storage/repository.go
> +	}
Обновил, убрал использование пакета http в слое репозитория

2024-07-22 15:57 UTC, tmvrus approved these changes

2024-07-22 16:13 UTC, merged