Iter5
igortoigildin/go-metrics-altering pull request #5
Opened 2024-06-05 11:52 UTC by igortoigildin

2024-06-07 11:58 UTC, tmvrus requested changes
идея собрать весь кода в cmd/ не самая лучшая
работать конечно будет, но развивать и модифировать кодовую базу будет сложно

2024-06-07 11:58 UTC, tmvrus commented on cmd/agent/main.go
> +	gaugeType = "gauge"
что-то тут с выравниванием

2024-06-07 11:58 UTC, tmvrus commented on cmd/agent/main.go
> +    rtm runtime.MemStats
и тут

2024-06-07 11:58 UTC, tmvrus commented on cmd/agent/flags.go
> +	err error
глобальные переменные это чаще всего плохая идея, особенно когда мы говорим о зыках в поддержкой многопоточности 
рекомендую сделать ф-я config() (Config, error) которая будет возвращать конфигуарацию и не будет использовать глобальные переменные

2024-06-07 11:58 UTC, tmvrus commented on cmd/agent/main.go
> +					panic(err)
сомнительное решение, если будет, например, сетевой сбой, то клиент упадет и уже больше ничего не отправит, даже если сеть починять через секунду

2024-06-07 11:58 UTC, tmvrus commented on cmd/agent/main.go
> +			panic(err)
то же что и выше

2024-06-07 11:58 UTC, tmvrus commented on cmd/agent/main.go
> +        time.Sleep(time.Duration(flagPollInterval) * time.Second)
time.Duration(flagPollInterval) * time.Second
можно было подсчитать один раз до начала цикла, а еще лучше передать сразу в аргументах UpdateMetrics что бы избежать работы с глобальной переменной

2024-06-07 11:58 UTC, tmvrus commented on cmd/agent/main.go
> +		memory["BuckHashSys"] = float64(rtm.BuckHashSys)
тут что-то с отступами

2024-06-07 11:58 UTC, tmvrus commented on cmd/server/main.go
> +	case "gauge":
для "gauge" и "counter" есть константы в агенте, почему бы не переменстить их в общую библиотеку и использовать и в агенте и в сервере

2024-06-07 11:58 UTC, tmvrus commented on cmd/server/main.go
> +        panic(err)
ошибка в теплейте уронит весь сервер, клиенты расстроятся 
возможно стоит парсить шаблон при старте сервера один раз?

2024-06-08 15:35 UTC, igortoigildin commented
> идея собрать весь кода в cmd/ не самая лучшая работать конечно будет, но развивать и модифировать кодовую базу будет сложно

исправил/перенес в другие директрории

2024-06-08 15:37 UTC, igortoigildin commented on cmd/agent/flags.go
> +	err error
добавил конфиг без использования глобальных переменных

2024-06-08 16:01 UTC, igortoigildin commented on cmd/agent/main.go
> +					panic(err)
поменял на вывод ошибки в консоль

2024-06-08 16:01 UTC, igortoigildin commented on cmd/agent/main.go
> +			panic(err)
поменял на вывод ошибки в консоль

2024-06-08 16:01 UTC, igortoigildin commented on cmd/agent/main.go
> +		memory["BuckHashSys"] = float64(rtm.BuckHashSys)
поправил

2024-06-08 16:09 UTC, igortoigildin commented on cmd/agent/main.go
> +        time.Sleep(time.Duration(flagPollInterval) * time.Second)
изменил функцию UpdateMetrics() в метод к структуре ConfigAgent где храним конфиги и метрики, так же вынес калькуляцию паузы из цикла

2024-06-08 16:26 UTC, igortoigildin commented on cmd/server/main.go
> +	case "gauge":
переместил константы в модуль конфиг в новой структуре проекта

2024-06-08 16:28 UTC, igortoigildin commented on cmd/server/main.go
> +        panic(err)
перенес парсинг шаблона в функцию MetricRouter, но пришлось добавить глобальную переменную *template.Template

2024-06-10 15:13 UTC, tmvrus approved these changes

2024-06-10 15:37 UTC, merged