Iter25
igortoigildin/go-metrics-altering pull request #62
Opened 2024-11-19 16:23 UTC by igortoigildin

2024-11-27 20:29 UTC, avhitrov requested changes
В общем, все рабочее, но в gRPC не реализована проверка на попадание клиента в подсеть. Отмечено в комментариях к коду.

2024-11-27 20:29 UTC, avhitrov commented on internal/agent/app/agent.go
> +			resp, err := m.AddGaugeMetric(context.Background(), &pb.AddGaugeRequest{
Контекст можно взять от приложения.

2024-11-27 20:29 UTC, avhitrov commented on internal/agent/app/agent.go
> +			logging.UnaryClientInterceptor(adapter.InterceptorLogger(logger), opts...),
В gRPC тоже необходимо пробрасывать аналог X-Real-IP (https://grpc.io/docs/guides/metadata/)

2024-11-27 20:29 UTC, avhitrov commented on internal/server/grpc/app/grpc/grpcapp.go
> +		logging.UnaryServerInterceptor(adapter.InterceptorLogger(logger), opts...),
Необходим интерсептор для проверки X-Real-IP

2024-11-29 16:40 UTC, igortoigildin commented on internal/agent/app/agent.go
> +			resp, err := m.AddGaugeMetric(context.Background(), &pb.AddGaugeRequest{
исправил

2024-11-30 12:08 UTC, igortoigildin commented on internal/agent/app/agent.go
> +			logging.UnaryClientInterceptor(adapter.InterceptorLogger(logger), opts...),
Добавил

2024-11-30 12:11 UTC, igortoigildin commented on internal/server/grpc/app/grpc/grpcapp.go
> +		logging.UnaryServerInterceptor(adapter.InterceptorLogger(logger), opts...),
Добавил realip interceptor

2024-12-03 19:24 UTC, avhitrov approved these changes
Все замечания исправлены. Отлично!

2024-12-04 07:27 UTC, merged